[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "ejs"]
  included_files = ["views/**", "data/**", "public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
